# DataSource Config
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://185.239.69.195:3306/hblog?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    sentinel:
      master: mymaster
      nodes: 47.106.38.101:26379,47.106.38.101:26380
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG